### ISSUE TITLE
Accessing the WP Reactivate settings page throws error

### ISSUE THREAD

**Issue by jfrankdev** [gopangolin/wp-reactivate#1]
Visiting this directory `/wp-admin/options-general.php?page=wp-reactivate` on my local Wordpress install throws this error in the console:

    Admin.jsx:16 Uncaught TypeError: Cannot read property 'api_url' of undefined at
    Admin._this.getSetting (Admin.jsx:16)

The error is referring to this function:

      getSetting = () => {
        fetch(`${this.props.wpObject.api_url}settings`, {
          credentials: 'same-origin',
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
            'X-WP-Nonce': this.props.wpObject.api_nonce,
          },
        })
        .then(response => response.json())
        .then(
          (json) => this.setState({ settings: json.wpreactivate }),
          (err) => console.log('error', err)
        );
      };

**Comment by dnusca** [comment]
Thanks for the bug report!

You can pull the latest master branch for the fix, or see it here - https://github.com/gopangolin/wp-reactivate/commit/cedc8173eb505ceea82bf9319e51d9460ac3dc67
