### ISSUE TITLE
local changes not showing up in the web app

### ISSUE THREAD

**Issue by congruentsquare** [gopangolin/wp-reactivate#3]
Changes to the admin panel are not showing up under settings. Even after I run the build command. 
Expecting the following to show up on the admin panel:
        ```
<h1>WP Reactivate Settings</h1>
        <form onSubmit={this.handleSubmit}>
          <label>
          Demo Setting:
            <input
              type="text"
              value={this.state.settings}
              onChange={this.updateInput}
            />
          </label>
          <input
            type="submit"
            id="submit"
            className="button button-primary"
            value={'Save'}
          />
```
but nothing mounts.

**Comment by JonathanMH** [comment]
@congruentsquare I believe that's because the API call returns `bool(true)` instead of the value that's inserted.

If you change

```
(json) => this.setState({ settings: json.wpreactivate }),
```
to
```
(json) => console.log(json),
```

it should be clear (and work on top of that)

**Comment by iaincoughtrie** [comment]
@congruentsquare I'm not sure I understand the problem. When you update `/containers/Admin.jsx` and build, the changes do not reflect in the settings panel?

I just tested again and all appears to be working. After you run `yarn build` or `npm run build`, any elements you've added or edited in `Admin.jsx` should be visible on the settings page.

**Comment by Mulli** [comment]
It works for me.
Set "Hello World" and its there even after visiting other admin panel entries.
Checked more and its under /wp-json/wp-reactivate/v1/settings
Hope that helps a bit

**Comment by iaincoughtrie** [comment]
We've just published the first part of our WP Reactivate tutorial series here - https://gopangolin.com/building-wordpress-plugin-with-react-part-1/.

Closing this issue.
