### ISSUE TITLE
Moving Plugin From Admin Settings to its own Admin Menu Item

### ISSUE THREAD

**Issue by JakeGreer** [gopangolin/wp-reactivate#8]
Hi awesome plugin this has been such a huge help for some projects that I have been working on. The only issue that I am having is when trying to move the plugin out from a sub item under Settings to its own admin menu item. Any ideas on how to go about this? Your help would be greatly appreciated thanks!

**Comment by dnusca** [comment]
You can use add_menu_page instead of add_options_page in the Admin class.
