### ISSUE TITLE
Cannot load css file from an external module.

### ISSUE THREAD

**Issue by reactone** [gopangolin/wp-reactivate#9]
I am trying to add [React Tostify](https://github.com/fkhadra/react-toastify) module on a clean install of your plugin as a shortcode and I have problems loading the css file from this module. I am loading the css file in shortcode.jsx via:

import 'react-toastify/dist/ReactToastify.css';

 I get the following error:

Uncaught Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .Toastify__toast-container

I've tried putting the css file in the same folder as the shortcode and play around with webpack.config.js but nothing seems to work. Any advice would be appreciated.

**Comment by reactone** [comment]
If anyone has the same problem - you will need to add a css loader to webpack.

**Comment by dnusca** [comment]
Closing as not related to actual plugin boilerplate but an external dependancy.
